[package]
name = "mnode_url"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = { version = "0.9.0", features = ["classes", "properties", "loader"] }
url = "2.5.7"
serde_json = "1.0.145"
mnode_utils = { path = "../mnode_utils" }
