[package]
name = "mnode_console"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = { version = "0.10.0", features = ["classes", "properties", "loader"] }
mnode_utils = { path = "../mnode_utils" }
